defaults: &defaults
  app:
    name: 'Scapp v2'
    host: 'scapp2.herokuapp.com'
    port: 3000
    default_locale: 'en'
    email:
      default: 'club@example.com'
      registration: 'register@example.com'
      no_reply: 'no_reply@example.com'

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
